### ISSUE TITLE
Expose assertion constructors (test a test library)

### ISSUE THREAD

**Issue by mchaver** [reasonml-community/bs-jest#15]
I am building a testing library for a particular task on top of Jest. I want to make sure my tests are returning the correct assertions. The way I was thinking of doing it was make sure it matches things like `Just Ok` and `Just (Fail message)` but that would require those types being exposed.

**Comment by glennsl** [comment]
The assertion type is, and should be, considered an implementation detail. But you should still be able to construct them through `Expect.*` and compare them for equality I think.

Alternatively, you can provide your own assertion type and function to the `Jest.Runner` functor, but that would of course mean you won't be able to use `Expect`.

You can also inspect the generated js value using a js function, or cast it to some other representation, like a reimplementation of the `assertion` type for example. This would of course be prone to break, but that's why it's internal in the first place.

**Comment by glennsl** [comment]
Closing this due to lack of confirmation. Reopen if you still have issues.

**Comment by mchaver** [comment]
@glennsl Sorry, forgot about this. I ignored it at the moment and worked on other things. I might come back to it in the future and try what you suggested.
