### ISSUE TITLE
Add assertion combinators 

### ISSUE THREAD

**Issue by dorafmon** [reasonml-community/bs-jest#8]
There is a lot of cases where I want to write something like this:

```
        test "Barray.set" (fun () ->
            let arr = [|1; 2; 3|] in
            let b = Barray.set 1 3 arr in
            Expect.toEqual b true `and` Expect.toEqual arr [|1; 3; 3|]
        );
```

So we can combine two assertions into one. Do you think this is possible? @glennsl 

Thanks!

**Comment by glennsl** [comment]
The thought has certainly crossed my mind, but I haven't really found any good use cases for it. Not that I've really looked all that much. Requiring a single assertion per test encourages simple tests, and I think your specific case here is a good example of that since it's trying to test two different properties at once.

I think it's good practice to design your tests around the properties you'd like tested instead of just "coverage".

**Comment by glennsl** [comment]
After some more thought and experience, I think enforcing a single assertion per test is still the right approach. Support for generating tests based on a set of test cases was added with `testAll` in #12, however, and might relieve some of the need you feel for combinators.

I'll close this for now, reopen if you find a scenario where you think the current tools are insufficient.
